# Generated by Django 4.0.3 on 2022-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Body'),
        ),
    ]
